/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemoteControlIndexRouteImport } from './routes/remote-control/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as RemoteControlBilibiliIndexRouteImport } from './routes/remote-control/bilibili/index'

const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/config/': typeof ConfigIndexRoute
    '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/config': typeof ConfigIndexRoute
    '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/config/': typeof ConfigIndexRoute
    '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/' | '/config/' | '/dashboard/'
    fileRoutesByTo: FileRoutesByTo
    to: '/' | '/config' | '/dashboard'
    id: '__root__' | '/' | '/config/' | '/dashboard/'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    ConfigIndexRoute: typeof ConfigIndexRoute
    DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/dashboard/': {
            id: '/dashboard/'
            path: '/dashboard'
            fullPath: '/dashboard/'
            preLoaderRoute: typeof DashboardIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/shutdown_control/config/': {
            id: '/shutdown_control/config/'
            path: '/shutdown_control/config'
            fullPath: '/shutdown_control/config/'
            preLoaderRoute: typeof Shutdown_controlConfigIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/remote-control/bilibili/': {
            id: '/remote-control/bilibili/'
            path: '/remote-control/bilibili'
            fullPath: '/remote-control/bilibili/'
            preLoaderRoute: typeof RemoteControlBilibiliIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ConfigIndexRoute: ConfigIndexRoute,
    DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
