/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Video_controlIndexRouteImport } from './routes/video_control/index'
import { Route as Shutdown_controlIndexRouteImport } from './routes/shutdown_control/index'
import { Route as Mqtt_configIndexRouteImport } from './routes/mqtt_config/index'
import { Route as Launch_appIndexRouteImport } from './routes/launch_app/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as Video_controlBilibiliIndexRouteImport } from './routes/video_control/bilibili/index'
import { Route as Shutdown_controlDashboardIndexRouteImport } from './routes/shutdown_control/dashboard/index'
import { Route as Shutdown_controlConfigIndexRouteImport } from './routes/shutdown_control/config/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Video_controlIndexRoute = Video_controlIndexRouteImport.update({
  id: '/video_control/',
  path: '/video_control/',
  getParentRoute: () => rootRouteImport,
} as any)
const Shutdown_controlIndexRoute = Shutdown_controlIndexRouteImport.update({
  id: '/shutdown_control/',
  path: '/shutdown_control/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mqtt_configIndexRoute = Mqtt_configIndexRouteImport.update({
  id: '/mqtt_config/',
  path: '/mqtt_config/',
  getParentRoute: () => rootRouteImport,
} as any)
const Launch_appIndexRoute = Launch_appIndexRouteImport.update({
  id: '/launch_app/',
  path: '/launch_app/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const Video_controlBilibiliIndexRoute =
  Video_controlBilibiliIndexRouteImport.update({
    id: '/video_control/bilibili/',
    path: '/video_control/bilibili/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Shutdown_controlDashboardIndexRoute =
  Shutdown_controlDashboardIndexRouteImport.update({
    id: '/shutdown_control/dashboard/',
    path: '/shutdown_control/dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Shutdown_controlConfigIndexRoute =
  Shutdown_controlConfigIndexRouteImport.update({
    id: '/shutdown_control/config/',
    path: '/shutdown_control/config/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/launch_app/': typeof Launch_appIndexRoute
  '/mqtt_config/': typeof Mqtt_configIndexRoute
  '/shutdown_control/': typeof Shutdown_controlIndexRoute
  '/video_control/': typeof Video_controlIndexRoute
  '/shutdown_control/config/': typeof Shutdown_controlConfigIndexRoute
  '/shutdown_control/dashboard/': typeof Shutdown_controlDashboardIndexRoute
  '/video_control/bilibili/': typeof Video_controlBilibiliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/launch_app': typeof Launch_appIndexRoute
  '/mqtt_config': typeof Mqtt_configIndexRoute
  '/shutdown_control': typeof Shutdown_controlIndexRoute
  '/video_control': typeof Video_controlIndexRoute
  '/shutdown_control/config': typeof Shutdown_controlConfigIndexRoute
  '/shutdown_control/dashboard': typeof Shutdown_controlDashboardIndexRoute
  '/video_control/bilibili': typeof Video_controlBilibiliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/launch_app/': typeof Launch_appIndexRoute
  '/mqtt_config/': typeof Mqtt_configIndexRoute
  '/shutdown_control/': typeof Shutdown_controlIndexRoute
  '/video_control/': typeof Video_controlIndexRoute
  '/shutdown_control/config/': typeof Shutdown_controlConfigIndexRoute
  '/shutdown_control/dashboard/': typeof Shutdown_controlDashboardIndexRoute
  '/video_control/bilibili/': typeof Video_controlBilibiliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/'
    | '/launch_app/'
    | '/mqtt_config/'
    | '/shutdown_control/'
    | '/video_control/'
    | '/shutdown_control/config/'
    | '/shutdown_control/dashboard/'
    | '/video_control/bilibili/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/launch_app'
    | '/mqtt_config'
    | '/shutdown_control'
    | '/video_control'
    | '/shutdown_control/config'
    | '/shutdown_control/dashboard'
    | '/video_control/bilibili'
  id:
    | '__root__'
    | '/'
    | '/home/'
    | '/launch_app/'
    | '/mqtt_config/'
    | '/shutdown_control/'
    | '/video_control/'
    | '/shutdown_control/config/'
    | '/shutdown_control/dashboard/'
    | '/video_control/bilibili/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  Launch_appIndexRoute: typeof Launch_appIndexRoute
  Mqtt_configIndexRoute: typeof Mqtt_configIndexRoute
  Shutdown_controlIndexRoute: typeof Shutdown_controlIndexRoute
  Video_controlIndexRoute: typeof Video_controlIndexRoute
  Shutdown_controlConfigIndexRoute: typeof Shutdown_controlConfigIndexRoute
  Shutdown_controlDashboardIndexRoute: typeof Shutdown_controlDashboardIndexRoute
  Video_controlBilibiliIndexRoute: typeof Video_controlBilibiliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video_control/': {
      id: '/video_control/'
      path: '/video_control'
      fullPath: '/video_control/'
      preLoaderRoute: typeof Video_controlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shutdown_control/': {
      id: '/shutdown_control/'
      path: '/shutdown_control'
      fullPath: '/shutdown_control/'
      preLoaderRoute: typeof Shutdown_controlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mqtt_config/': {
      id: '/mqtt_config/'
      path: '/mqtt_config'
      fullPath: '/mqtt_config/'
      preLoaderRoute: typeof Mqtt_configIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch_app/': {
      id: '/launch_app/'
      path: '/launch_app'
      fullPath: '/launch_app/'
      preLoaderRoute: typeof Launch_appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video_control/bilibili/': {
      id: '/video_control/bilibili/'
      path: '/video_control/bilibili'
      fullPath: '/video_control/bilibili/'
      preLoaderRoute: typeof Video_controlBilibiliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shutdown_control/dashboard/': {
      id: '/shutdown_control/dashboard/'
      path: '/shutdown_control/dashboard'
      fullPath: '/shutdown_control/dashboard/'
      preLoaderRoute: typeof Shutdown_controlDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shutdown_control/config/': {
      id: '/shutdown_control/config/'
      path: '/shutdown_control/config'
      fullPath: '/shutdown_control/config/'
      preLoaderRoute: typeof Shutdown_controlConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  Launch_appIndexRoute: Launch_appIndexRoute,
  Mqtt_configIndexRoute: Mqtt_configIndexRoute,
  Shutdown_controlIndexRoute: Shutdown_controlIndexRoute,
  Video_controlIndexRoute: Video_controlIndexRoute,
  Shutdown_controlConfigIndexRoute: Shutdown_controlConfigIndexRoute,
  Shutdown_controlDashboardIndexRoute: Shutdown_controlDashboardIndexRoute,
  Video_controlBilibiliIndexRoute: Video_controlBilibiliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
