[jobs.main]   # 任务名称可自定义
command = ["cargo", "run"]
env = { RUSTFLAGS = "-Awarnings" }
need_stdout = true
background = false                # 标记为前台程序
on_change_strategy = "kill_then_restart"  # 变化时重启
