[package]
name = "remote-computer"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.4.3"
axum = {version="0.8.9",features=["ws"]}
tower-http = { version = "0.6.10", features = ["cors", "fs"] }
mio = "1.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["full"] }
tokio-rustls = "0.26.4"
rustls-pemfile = "2.2.0"
rustls = { version = "0.23.4", features = ["ring"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
hyper = "1.9.0"
http = "1.4.0"
toml = "1.1.2"
sysinfo = "0.39.0"
chrono = {version="0.4.44",features=["serde"]}
rumqttc = "0.25.1"
open = "5.3.4"
smol = "2.0.2"
rmqtt = { version = "0.21.0", features = ["ws"] }
simple_logger = "5.2.0"
log = "0.4.32"
volumecontrol = "0.1.4"
anyhow = "1.0.102"
cpvc = "0.6.0"
env_logger = "0.11.10"
dirs = "6.0.0"
home = "0.5.12"
axum-extra = {version="0.12.6",features=["typed-header"]}
futures-util = "0.3.34"
dotenvy = "0.15.7"
include_dir = "0.7.4"
tower = "0.5.3"
mime_guess = "2.0.5"
